apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-decode
  namespace: api-gateway-system
  labels:
    app.kubernetes.io/instance: jwt-decode
    app.kubernetes.io/managed-by: tmax-cloud
    app.kubernetes.io/name: jwt-decode
data:
  config.json: |
    {}
