apiVersion: v1
kind: Service
metadata:
  name: jwt-decode
  namespace: api-gateway-system
  labels:
    app.kubernetes.io/instance: jwt-decode
    app.kubernetes.io/managed-by: tmax-cloud
    app.kubernetes.io/name: jwt-decode
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: jwt-decode
    app.kubernetes.io/name: jwt-decode
