kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "traefik-jwt-decode.fullname" . }}-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
